### ISSUE TITLE
spi flash

### ISSUE THREAD

**Issue by koendv** [WeActTC/BluePill-Plus#11]
Thank you for this board. I have a question, On the back of the blue pill plus there is place to solder a W25Q64 spi flash. If I look at the datasheet of the GD32F303, the GD32F303 can connect quad spi flash (SPI0_IO2 on PA2, SPI0_IO3 on PA3). But if I look at the schematic and the board, quad spi is not used? Only single spi?

**Comment by Liuyufanlyf** [comment]
Well, although GD32F303 has QSPI, it seldom needs such a high-speed transmission. WeactStudio's STM32H7 board has a QSPI Flash because STM32H7 supports XIP through QSPI, but GD32F303 doesn't. And this board is compatible with STM32F1, which doesn't have QSPI peripheral.

**Comment by koendv** [comment]
ok
