### ISSUE TITLE
arduino question

### ISSUE THREAD

**Issue by koendv** [WeActTC/BluePill-Plus#8]
Thank you for an interesting board. I have a question. could this board run micropyhon, or, with a spi ram added, openmv?

**Comment by koendv** [comment]
I did not find a micropython port. 

There is support for Arduino: 
https://github.com/CommunityGD32Cores/ArduinoCore-GD32

and Huawei LiteOS also runs:
https://github.com/koendv/liteos-bluepillplus

koen

**Comment by rohit-kumar-j** [comment]
@koendv Thanks for the quick reply!

I'm sure if this is the correct reason, but the lack of support seems to be the lower capacity of Ram (64Kb). Hence there is not much benefit for using an stm32 with micropython on this board if the support libraries, etc take up almost the entire space.
